# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from omoros/R1MotorStatusLR.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import omoros.msg
import std_msgs.msg

class R1MotorStatusLR(genpy.Message):
  _md5sum = "d4f43c45f2af2c6f8fc40d2ec2c98367"
  _type = "omoros/R1MotorStatusLR"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
float32 Vspeed   	# mm per second
float32 Vomega	    # mrad per second
R1MotorStatus left
R1MotorStatus right

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: omoros/R1MotorStatus
bool low_voltage
bool overloaded
int8 power      # PWM duty cycle -100 ... 100
float32 encoder # degree
float32 RPM   	# degree per second
float32 ODO	    # odometry
float32 speed   # mm per second
"""
  __slots__ = ['header','Vspeed','Vomega','left','right']
  _slot_types = ['std_msgs/Header','float32','float32','omoros/R1MotorStatus','omoros/R1MotorStatus']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,Vspeed,Vomega,left,right

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(R1MotorStatusLR, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.Vspeed is None:
        self.Vspeed = 0.
      if self.Vomega is None:
        self.Vomega = 0.
      if self.left is None:
        self.left = omoros.msg.R1MotorStatus()
      if self.right is None:
        self.right = omoros.msg.R1MotorStatus()
    else:
      self.header = std_msgs.msg.Header()
      self.Vspeed = 0.
      self.Vomega = 0.
      self.left = omoros.msg.R1MotorStatus()
      self.right = omoros.msg.R1MotorStatus()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2f2Bb4f2Bb4f().pack(_x.Vspeed, _x.Vomega, _x.left.low_voltage, _x.left.overloaded, _x.left.power, _x.left.encoder, _x.left.RPM, _x.left.ODO, _x.left.speed, _x.right.low_voltage, _x.right.overloaded, _x.right.power, _x.right.encoder, _x.right.RPM, _x.right.ODO, _x.right.speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.left is None:
        self.left = omoros.msg.R1MotorStatus()
      if self.right is None:
        self.right = omoros.msg.R1MotorStatus()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 46
      (_x.Vspeed, _x.Vomega, _x.left.low_voltage, _x.left.overloaded, _x.left.power, _x.left.encoder, _x.left.RPM, _x.left.ODO, _x.left.speed, _x.right.low_voltage, _x.right.overloaded, _x.right.power, _x.right.encoder, _x.right.RPM, _x.right.ODO, _x.right.speed,) = _get_struct_2f2Bb4f2Bb4f().unpack(str[start:end])
      self.left.low_voltage = bool(self.left.low_voltage)
      self.left.overloaded = bool(self.left.overloaded)
      self.right.low_voltage = bool(self.right.low_voltage)
      self.right.overloaded = bool(self.right.overloaded)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2f2Bb4f2Bb4f().pack(_x.Vspeed, _x.Vomega, _x.left.low_voltage, _x.left.overloaded, _x.left.power, _x.left.encoder, _x.left.RPM, _x.left.ODO, _x.left.speed, _x.right.low_voltage, _x.right.overloaded, _x.right.power, _x.right.encoder, _x.right.RPM, _x.right.ODO, _x.right.speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.left is None:
        self.left = omoros.msg.R1MotorStatus()
      if self.right is None:
        self.right = omoros.msg.R1MotorStatus()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 46
      (_x.Vspeed, _x.Vomega, _x.left.low_voltage, _x.left.overloaded, _x.left.power, _x.left.encoder, _x.left.RPM, _x.left.ODO, _x.left.speed, _x.right.low_voltage, _x.right.overloaded, _x.right.power, _x.right.encoder, _x.right.RPM, _x.right.ODO, _x.right.speed,) = _get_struct_2f2Bb4f2Bb4f().unpack(str[start:end])
      self.left.low_voltage = bool(self.left.low_voltage)
      self.left.overloaded = bool(self.left.overloaded)
      self.right.low_voltage = bool(self.right.low_voltage)
      self.right.overloaded = bool(self.right.overloaded)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_2f2Bb4f2Bb4f = None
def _get_struct_2f2Bb4f2Bb4f():
    global _struct_2f2Bb4f2Bb4f
    if _struct_2f2Bb4f2Bb4f is None:
        _struct_2f2Bb4f2Bb4f = struct.Struct("<2f2Bb4f2Bb4f")
    return _struct_2f2Bb4f2Bb4f
